[package]
name = "timed"
version = "0.1.0"
authors = ["Prajith <kprajith@amazon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
timed_macro = {path = "./src/macros"}
proc-macro-hack = "0.5"






